version: '3'

volumes:
  postgres_data:
      driver: local

services:        
  postgres_keycloak:
    image: postgres:9.5
    hostname: hostname_postgres_keycloak
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
        - postgres_data:/var/lib/postgresql/
        
  keycloak:
      image: quay.io/keycloak/keycloak:20.0
      command: start-dev
      container_name: keycloak
      environment:
        TZ: America/Recife
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres_keycloak
        DB_DATABASE: keycloak_db
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: keycloak
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HTTP_RELATIVE_PATH: /auth
        #KC_HOSTNAME_URL: https://gateway-xxxxxxxx.yyyyyyy.com:8443
        #KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
        #KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      ports:
        - 8080:8080
      depends_on:
        - postgres_keycloak