version: '3'

volumes:
  postgres_data:
      driver: local

services:        
  postgres_keycloak:
    image: postgres:9.5
    hostname: hostname_postgres_keycloak
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
        - postgres_data:/var/lib/postgresql/
        
  keycloak:
      image: bitnami/keycloak:22.0.2-debian-11-r0
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres_keycloak
        DB_DATABASE: keycloak_db
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres_keycloak